task :run_tests do
  require_relative './test/Players/tc_player_type.rb'
  ruby 'test/Players/tc_player_manager_initialization.rb'
  ruby 'test/Players/tc_player_manager.rb'
  ruby 'test/Players/tc_player.rb'
  ruby 'test/Players/tc_player_movement_manager.rb'
  ruby 'test/GamePlay/tc_match_type.rb'
  ruby 'test/GamePlay/tc_match_type_manager.rb'
  ruby 'test/GamePlay/tc_game_board.rb'
  ruby 'test/GamePlay/tc_computer_actions.rb'
  ruby 'test/Validators/tc_available_spaces_validation.rb'
  ruby 'test/Validators/tc_game_over_validation.rb'
  ruby 'test/Validators/tc_game_play_validation.rb'
  ruby 'test/Validators/tc_player_selection_validation.rb'
  ruby 'test/Validators/tc_player_symbol_validation.rb'
  ruby 'test/Validators/tc_tie_game_validation.rb'
  ruby 'test/Evaluators/tc_board_score_evaluation_parameterized_tests.rb'
  ruby 'test/Evaluators/tc_board_score_evaluation.rb'
end
