Gem::Specification.new do |s|
  s.name        = 'tic_tac_toe_rz'
  s.version     = '1.0.05'
  s.date        = '2018-04-25'
  s.summary     = "Tic Tac Toe API"
  s.description = "Tic Tac Toe API written in Ruby"
  s.authors     = ["Rani Zilpelwar"]
  s.email       = 'rani@8thlight.com'
  s.files       = ["lib/tic_tac_toe_rz.rb", 
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Config/application_text.en.yaml", 
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Config/application_text.es.yaml", 
    "lib/tic_tac_toe_rz/tictactoeruby.core/config/global_settings.yaml",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Config/language_options.en.yaml", 
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Config/language_options.es.yaml",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Evaluators/board_score_evaluator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Evaluators/player_symbol_evaluator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Exceptions/invalid_value_error.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Exceptions/nil_reference_error.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Exceptions/player_type_error.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Exceptions/game_rule_violation_error.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/GamePlay/computer_actions.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/GamePlay/game_board.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/GamePlay/match_type_manager.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/GamePlay/match_type.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/GamePlay/weighted_move.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Languages/language_config.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Languages/language_options_adapter.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Languages/language.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Languages/message_generator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Languages/yaml_reader.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Languages/yaml_writer.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Players/player_manager.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Players/player_movement_manager.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Players/player_type.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Players/player.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Validators/available_spaces_validator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Validators/game_over_validator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Validators/game_play_validator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Validators/input_validator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Validators/player_selection_validator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Validators/player_symbol_validator.rb",
    "lib/tic_tac_toe_rz/TicTacToeRuby.Core/Validators/tie_game_validator.rb",
	  "features/board.feature",
		"features/computer_actions.feature",
		"features/game_over.feature",
		"features/language_options.feature",
		"features/match.feature",
		"features/step_definitions/board_steps.rb",
		"features/step_definitions/computer_actions_steps.rb",
		"features/step_definitions/game_over_steps.rb",
		"features/step_definitions/language_options_steps.rb",
		"features/step_definitions/match_steps.rb",
		"features/step_definitions/players_steps.rb",
	  "features/test_files/bad_global_settings/global_settings.yaml",
	  "features/test_files/bad_global_settings/language_options.en.yaml",
	  "features/test_files/default_language_english/global_settings.yaml",
	  "features/test_files/default_language_english/language_options.en.yaml",
	  "features/test_files/default_language_english/language_options.es.yaml",
	  "features/test_files/default_language_spanish/global_settings.yaml",
	  "features/test_files/default_language_spanish/language_options.en.yaml",
	  "features/test_files/default_language_spanish/language_options.es.yaml",
	  "spec/Evaluators/board_score_evaluator_spec.rb",
	  "spec/GamePlay/board_spec.rb",
	  "spec/GamePlay/computer_actions_spec.rb",
	  "spec/GamePlay/doubles.rb",
	  "spec/GamePlay/game_board_spec.rb",
	  "spec/GamePlay/game_spec.rb",
	  "spec/GamePlay/match_spec.rb",
	  "spec/GamePlay/match_type_manager_spec.rb",
	  "spec/Languages/language_options_adapter_spec.rb",
	  "spec/Languages/yaml_reader_spec.rb",
	  "spec/Languages/yaml_writer_spec.rb",
	  "spec/Players/player_manager_spec.rb",
	  "spec/Players/player_movement_manager_spec.rb",
	  "spec/Players/player_spec.rb",
	  "spec/Players/player_type_spec.rb",
	  "spec/TestFiles/testing.en.yaml",
	  "spec/Validators/available_spaces_validator_spec.rb",
	  "spec/Validators/game_over_validator_spec.rb",
	  "spec/Validators/game_play_validator_spec.rb",
	  "spec/Validators/player_selection_validator_spec.rb",
	  "spec/Validators/player_symbol_validator_spec.rb",
	  "spec/Validators/tie_game_validator_spec.rb",
	  "test/Evaluators/tc_board_score_evaluation.rb",
	  "test/Evaluators/tc_board_score_evaluation_parameterized_tests.rb",
	  "test/GamePlay/tc_computer_actions.rb",
	  "test/GamePlay/tc_game_board.rb",
	  "test/GamePlay/tc_match_type.rb",
	  "test/GamePlay/tc_match_type_manager.rb",
		"test/Players/mock_player_manager.rb",
		"test/Players/tc_player.rb",
  	"test/Players/tc_player_manager.rb",
		"test/Players/tc_player_manager_initialization.rb",
		"test/Players/tc_player_movement_manager.rb",
		"test/Players/tc_player_type.rb",
		"test/Validators/tc_available_spaces_validation.rb",
		"test/Validators/tc_game_over_validation.rb",
		"test/Validators/tc_game_play_validation.rb",
		"test/Validators/tc_player_selection_validation.rb",
		"test/Validators/tc_player_symbol_validation.rb",
		"test/Validators/tc_tie_game_validation.rb"]
  s.homepage    =
    'http://rubygems.org'
  s.license       = 'MIT'
end
